$(function(){
		obj={
			search:function(){
				$('#link1').datagrid('load',{
					linkName:$.trim($('input[name="linkName"]').val()),
					date_from:$.trim($('input[name="date_from"]').val()),
					date_to:$.trim($('input[name="date_to"]').val()),
				});
			},
		};
		$('#link1').datagrid({
			url:'link.json',
			title:'链接列表',
			iconCls:'icon-save',
			idField:'itemId',
			
			columns:[[
					{
						checkbox:true,
						title:'编号',
						field:'id'
					  },
			          {
						title:'链接名称',
						field:'linkName',
						editor:{
								type:'validatebox',
								options:{required:true}
							}
							
				      },{
				    	 title:'链接',
						 field:'link',
						 editor:{
								type:'validatebox',
								options:{required:true}
							}
					  },{
						  title:'创建时间',
						  field:'date'
					  }
					]],
			pagination:true,
			toolbar:'#tb',
			/*toolbar:[
			{
				text:'修改',
				iconCls:'icon-edit',
				handler:function(){}
			},'-',
			{
				text:'增加',
				iconCls:'icon-add',
				handler:function(){}
			},'-',
			{
				text:'删除',
				iconCls:'icon-remove',
				handler:function(){}
			}],*/
		});
	});